project_id = "jgkmyyxrtgcfhcnieegw"

[functions.fetch-dolar]
verify_jwt = false

[functions.fetch-noticias-agro]
verify_jwt = false

[functions.buscar-cotacoes]
verify_jwt = true

[functions.fetch-clima]
verify_jwt = false

[functions.check-alertas-preco]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-setup]
verify_jwt = true

[functions.stripe-webhook-setup]
verify_jwt = true

[functions.create-portal-session]
verify_jwt = true

[functions.enviar-convite]
verify_jwt = true

[functions.enviar-contato]
verify_jwt = false





[functions.admin-criar-demo]
verify_jwt = true

[functions.admin-demo-reset-senha]
verify_jwt = true

[functions.admin-demo-apagar]
verify_jwt = true
