project_id = "jgkmyyxrtgcfhcnieegw"

[functions.fetch-dolar]
verify_jwt = false

[functions.fetch-noticias-agro]
verify_jwt = false

[functions.buscar-cotacoes]
verify_jwt = true

[functions.fetch-clima]
verify_jwt = false

[functions.check-alertas-preco]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.stripe-setup]
verify_jwt = true

