/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompletarCadastroRouteImport } from './routes/completar-cadastro'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BloqueadoRouteImport } from './routes/bloqueado'
import { Route as AguardandoAprovacaoRouteImport } from './routes/aguardando-aprovacao'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated.painel'
import { Route as AuthenticatedNoticiasRouteImport } from './routes/_authenticated.noticias'
import { Route as AuthenticatedCotacaoRouteImport } from './routes/_authenticated.cotacao'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated.configuracoes'
import { Route as AuthenticatedComprarRouteImport } from './routes/_authenticated.comprar'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated.alertas'
import { Route as AuthenticatedVenderIndexRouteImport } from './routes/_authenticated.vender.index'
import { Route as AuthenticatedMensagensIndexRouteImport } from './routes/_authenticated.mensagens.index'
import { Route as AuthenticatedVenderNovoRouteImport } from './routes/_authenticated.vender.novo'
import { Route as AuthenticatedMensagensConversaIdRouteImport } from './routes/_authenticated.mensagens.$conversaId'
import { Route as AuthenticatedAnuncioIdRouteImport } from './routes/_authenticated.anuncio.$id'
import { Route as AuthenticatedAdminCotacoesRouteImport } from './routes/_authenticated.admin.cotacoes'
import { Route as AuthenticatedVenderEditarIdRouteImport } from './routes/_authenticated.vender.editar.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletarCadastroRoute = CompletarCadastroRouteImport.update({
  id: '/completar-cadastro',
  path: '/completar-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BloqueadoRoute = BloqueadoRouteImport.update({
  id: '/bloqueado',
  path: '/bloqueado',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoAprovacaoRoute = AguardandoAprovacaoRouteImport.update({
  id: '/aguardando-aprovacao',
  path: '/aguardando-aprovacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNoticiasRoute = AuthenticatedNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCotacaoRoute = AuthenticatedCotacaoRouteImport.update({
  id: '/cotacao',
  path: '/cotacao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComprarRoute = AuthenticatedComprarRouteImport.update({
  id: '/comprar',
  path: '/comprar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVenderIndexRoute =
  AuthenticatedVenderIndexRouteImport.update({
    id: '/vender/',
    path: '/vender/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMensagensIndexRoute =
  AuthenticatedMensagensIndexRouteImport.update({
    id: '/mensagens/',
    path: '/mensagens/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVenderNovoRoute = AuthenticatedVenderNovoRouteImport.update({
  id: '/vender/novo',
  path: '/vender/novo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMensagensConversaIdRoute =
  AuthenticatedMensagensConversaIdRouteImport.update({
    id: '/mensagens/$conversaId',
    path: '/mensagens/$conversaId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnuncioIdRoute = AuthenticatedAnuncioIdRouteImport.update({
  id: '/anuncio/$id',
  path: '/anuncio/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminCotacoesRoute =
  AuthenticatedAdminCotacoesRouteImport.update({
    id: '/admin/cotacoes',
    path: '/admin/cotacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVenderEditarIdRoute =
  AuthenticatedVenderEditarIdRouteImport.update({
    id: '/vender/editar/$id',
    path: '/vender/editar/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/bloqueado': typeof BloqueadoRoute
  '/cadastro': typeof CadastroRoute
  '/completar-cadastro': typeof CompletarCadastroRoute
  '/login': typeof LoginRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/comprar': typeof AuthenticatedComprarRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/cotacao': typeof AuthenticatedCotacaoRoute
  '/noticias': typeof AuthenticatedNoticiasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/admin/cotacoes': typeof AuthenticatedAdminCotacoesRoute
  '/anuncio/$id': typeof AuthenticatedAnuncioIdRoute
  '/mensagens/$conversaId': typeof AuthenticatedMensagensConversaIdRoute
  '/vender/novo': typeof AuthenticatedVenderNovoRoute
  '/mensagens/': typeof AuthenticatedMensagensIndexRoute
  '/vender/': typeof AuthenticatedVenderIndexRoute
  '/vender/editar/$id': typeof AuthenticatedVenderEditarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/bloqueado': typeof BloqueadoRoute
  '/cadastro': typeof CadastroRoute
  '/completar-cadastro': typeof CompletarCadastroRoute
  '/login': typeof LoginRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/comprar': typeof AuthenticatedComprarRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/cotacao': typeof AuthenticatedCotacaoRoute
  '/noticias': typeof AuthenticatedNoticiasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/admin/cotacoes': typeof AuthenticatedAdminCotacoesRoute
  '/anuncio/$id': typeof AuthenticatedAnuncioIdRoute
  '/mensagens/$conversaId': typeof AuthenticatedMensagensConversaIdRoute
  '/vender/novo': typeof AuthenticatedVenderNovoRoute
  '/mensagens': typeof AuthenticatedMensagensIndexRoute
  '/vender': typeof AuthenticatedVenderIndexRoute
  '/vender/editar/$id': typeof AuthenticatedVenderEditarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/bloqueado': typeof BloqueadoRoute
  '/cadastro': typeof CadastroRoute
  '/completar-cadastro': typeof CompletarCadastroRoute
  '/login': typeof LoginRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/comprar': typeof AuthenticatedComprarRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/cotacao': typeof AuthenticatedCotacaoRoute
  '/_authenticated/noticias': typeof AuthenticatedNoticiasRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/admin/cotacoes': typeof AuthenticatedAdminCotacoesRoute
  '/_authenticated/anuncio/$id': typeof AuthenticatedAnuncioIdRoute
  '/_authenticated/mensagens/$conversaId': typeof AuthenticatedMensagensConversaIdRoute
  '/_authenticated/vender/novo': typeof AuthenticatedVenderNovoRoute
  '/_authenticated/mensagens/': typeof AuthenticatedMensagensIndexRoute
  '/_authenticated/vender/': typeof AuthenticatedVenderIndexRoute
  '/_authenticated/vender/editar/$id': typeof AuthenticatedVenderEditarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aguardando-aprovacao'
    | '/bloqueado'
    | '/cadastro'
    | '/completar-cadastro'
    | '/login'
    | '/alertas'
    | '/comprar'
    | '/configuracoes'
    | '/cotacao'
    | '/noticias'
    | '/painel'
    | '/admin/cotacoes'
    | '/anuncio/$id'
    | '/mensagens/$conversaId'
    | '/vender/novo'
    | '/mensagens/'
    | '/vender/'
    | '/vender/editar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aguardando-aprovacao'
    | '/bloqueado'
    | '/cadastro'
    | '/completar-cadastro'
    | '/login'
    | '/alertas'
    | '/comprar'
    | '/configuracoes'
    | '/cotacao'
    | '/noticias'
    | '/painel'
    | '/admin/cotacoes'
    | '/anuncio/$id'
    | '/mensagens/$conversaId'
    | '/vender/novo'
    | '/mensagens'
    | '/vender'
    | '/vender/editar/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aguardando-aprovacao'
    | '/bloqueado'
    | '/cadastro'
    | '/completar-cadastro'
    | '/login'
    | '/_authenticated/alertas'
    | '/_authenticated/comprar'
    | '/_authenticated/configuracoes'
    | '/_authenticated/cotacao'
    | '/_authenticated/noticias'
    | '/_authenticated/painel'
    | '/_authenticated/admin/cotacoes'
    | '/_authenticated/anuncio/$id'
    | '/_authenticated/mensagens/$conversaId'
    | '/_authenticated/vender/novo'
    | '/_authenticated/mensagens/'
    | '/_authenticated/vender/'
    | '/_authenticated/vender/editar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AguardandoAprovacaoRoute: typeof AguardandoAprovacaoRoute
  BloqueadoRoute: typeof BloqueadoRoute
  CadastroRoute: typeof CadastroRoute
  CompletarCadastroRoute: typeof CompletarCadastroRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completar-cadastro': {
      id: '/completar-cadastro'
      path: '/completar-cadastro'
      fullPath: '/completar-cadastro'
      preLoaderRoute: typeof CompletarCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloqueado': {
      id: '/bloqueado'
      path: '/bloqueado'
      fullPath: '/bloqueado'
      preLoaderRoute: typeof BloqueadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando-aprovacao': {
      id: '/aguardando-aprovacao'
      path: '/aguardando-aprovacao'
      fullPath: '/aguardando-aprovacao'
      preLoaderRoute: typeof AguardandoAprovacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/noticias': {
      id: '/_authenticated/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof AuthenticatedNoticiasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cotacao': {
      id: '/_authenticated/cotacao'
      path: '/cotacao'
      fullPath: '/cotacao'
      preLoaderRoute: typeof AuthenticatedCotacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comprar': {
      id: '/_authenticated/comprar'
      path: '/comprar'
      fullPath: '/comprar'
      preLoaderRoute: typeof AuthenticatedComprarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vender/': {
      id: '/_authenticated/vender/'
      path: '/vender'
      fullPath: '/vender/'
      preLoaderRoute: typeof AuthenticatedVenderIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mensagens/': {
      id: '/_authenticated/mensagens/'
      path: '/mensagens'
      fullPath: '/mensagens/'
      preLoaderRoute: typeof AuthenticatedMensagensIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vender/novo': {
      id: '/_authenticated/vender/novo'
      path: '/vender/novo'
      fullPath: '/vender/novo'
      preLoaderRoute: typeof AuthenticatedVenderNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mensagens/$conversaId': {
      id: '/_authenticated/mensagens/$conversaId'
      path: '/mensagens/$conversaId'
      fullPath: '/mensagens/$conversaId'
      preLoaderRoute: typeof AuthenticatedMensagensConversaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/anuncio/$id': {
      id: '/_authenticated/anuncio/$id'
      path: '/anuncio/$id'
      fullPath: '/anuncio/$id'
      preLoaderRoute: typeof AuthenticatedAnuncioIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/cotacoes': {
      id: '/_authenticated/admin/cotacoes'
      path: '/admin/cotacoes'
      fullPath: '/admin/cotacoes'
      preLoaderRoute: typeof AuthenticatedAdminCotacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vender/editar/$id': {
      id: '/_authenticated/vender/editar/$id'
      path: '/vender/editar/$id'
      fullPath: '/vender/editar/$id'
      preLoaderRoute: typeof AuthenticatedVenderEditarIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedComprarRoute: typeof AuthenticatedComprarRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCotacaoRoute: typeof AuthenticatedCotacaoRoute
  AuthenticatedNoticiasRoute: typeof AuthenticatedNoticiasRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedAdminCotacoesRoute: typeof AuthenticatedAdminCotacoesRoute
  AuthenticatedAnuncioIdRoute: typeof AuthenticatedAnuncioIdRoute
  AuthenticatedMensagensConversaIdRoute: typeof AuthenticatedMensagensConversaIdRoute
  AuthenticatedVenderNovoRoute: typeof AuthenticatedVenderNovoRoute
  AuthenticatedMensagensIndexRoute: typeof AuthenticatedMensagensIndexRoute
  AuthenticatedVenderIndexRoute: typeof AuthenticatedVenderIndexRoute
  AuthenticatedVenderEditarIdRoute: typeof AuthenticatedVenderEditarIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedComprarRoute: AuthenticatedComprarRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCotacaoRoute: AuthenticatedCotacaoRoute,
  AuthenticatedNoticiasRoute: AuthenticatedNoticiasRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedAdminCotacoesRoute: AuthenticatedAdminCotacoesRoute,
  AuthenticatedAnuncioIdRoute: AuthenticatedAnuncioIdRoute,
  AuthenticatedMensagensConversaIdRoute: AuthenticatedMensagensConversaIdRoute,
  AuthenticatedVenderNovoRoute: AuthenticatedVenderNovoRoute,
  AuthenticatedMensagensIndexRoute: AuthenticatedMensagensIndexRoute,
  AuthenticatedVenderIndexRoute: AuthenticatedVenderIndexRoute,
  AuthenticatedVenderEditarIdRoute: AuthenticatedVenderEditarIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AguardandoAprovacaoRoute: AguardandoAprovacaoRoute,
  BloqueadoRoute: BloqueadoRoute,
  CadastroRoute: CadastroRoute,
  CompletarCadastroRoute: CompletarCadastroRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
