/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConhecaRouteImport } from './routes/conheca'
import { Route as CompletarCadastroRouteImport } from './routes/completar-cadastro'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BloqueadoRouteImport } from './routes/bloqueado'
import { Route as AguardandoAprovacaoRouteImport } from './routes/aguardando-aprovacao'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParaPerfilRouteImport } from './routes/para.$perfil'
import { Route as AuthenticatedVenderRouteImport } from './routes/_authenticated.vender'
import { Route as AuthenticatedStartupsRouteImport } from './routes/_authenticated.startups'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated.relatorios'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated.planos'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated.painel'
import { Route as AuthenticatedNoticiasRouteImport } from './routes/_authenticated.noticias'
import { Route as AuthenticatedNegociacoesRouteImport } from './routes/_authenticated.negociacoes'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated.mensagens'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated.financeiro'
import { Route as AuthenticatedCotacaoRouteImport } from './routes/_authenticated.cotacao'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated.conta'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated.configuracoes'
import { Route as AuthenticatedComprarRouteImport } from './routes/_authenticated.comprar'
import { Route as AuthenticatedClubeRouteImport } from './routes/_authenticated.clube'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated.alertas'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated.agenda'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedVenderIndexRouteImport } from './routes/_authenticated.vender.index'
import { Route as AuthenticatedMensagensIndexRouteImport } from './routes/_authenticated.mensagens.index'
import { Route as AuthenticatedCursosIndexRouteImport } from './routes/_authenticated.cursos.index'
import { Route as AuthenticatedCertificadosIndexRouteImport } from './routes/_authenticated.certificados.index'
import { Route as AuthenticatedVenderNovoRouteImport } from './routes/_authenticated.vender.novo'
import { Route as AuthenticatedMensagensConversaIdRouteImport } from './routes/_authenticated.mensagens.$conversaId'
import { Route as AuthenticatedCursosIdRouteImport } from './routes/_authenticated.cursos.$id'
import { Route as AuthenticatedCertificadoCodigoRouteImport } from './routes/_authenticated.certificado.$codigo'
import { Route as AuthenticatedAnuncioIdRouteImport } from './routes/_authenticated.anuncio.$id'
import { Route as AuthenticatedAdminVantagensRouteImport } from './routes/_authenticated.admin.vantagens'
import { Route as AuthenticatedAdminModeracaoRouteImport } from './routes/_authenticated.admin.moderacao'
import { Route as AuthenticatedAdminGestaoRouteImport } from './routes/_authenticated.admin.gestao'
import { Route as AuthenticatedAdminCursosRouteImport } from './routes/_authenticated.admin.cursos'
import { Route as AuthenticatedAdminCotacoesRouteImport } from './routes/_authenticated.admin.cotacoes'
import { Route as AuthenticatedAdminContatosRouteImport } from './routes/_authenticated.admin.contatos'
import { Route as AuthenticatedAdminCatalogoRouteImport } from './routes/_authenticated.admin.catalogo'
import { Route as AuthenticatedAdminAcessosRouteImport } from './routes/_authenticated.admin.acessos'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedVenderEditarIdRouteImport } from './routes/_authenticated.vender.editar.$id'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConhecaRoute = ConhecaRouteImport.update({
  id: '/conheca',
  path: '/conheca',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletarCadastroRoute = CompletarCadastroRouteImport.update({
  id: '/completar-cadastro',
  path: '/completar-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BloqueadoRoute = BloqueadoRouteImport.update({
  id: '/bloqueado',
  path: '/bloqueado',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoAprovacaoRoute = AguardandoAprovacaoRouteImport.update({
  id: '/aguardando-aprovacao',
  path: '/aguardando-aprovacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaPerfilRoute = ParaPerfilRouteImport.update({
  id: '/para/$perfil',
  path: '/para/$perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVenderRoute = AuthenticatedVenderRouteImport.update({
  id: '/vender',
  path: '/vender',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStartupsRoute = AuthenticatedStartupsRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNoticiasRoute = AuthenticatedNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNegociacoesRoute =
  AuthenticatedNegociacoesRouteImport.update({
    id: '/negociacoes',
    path: '/negociacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCotacaoRoute = AuthenticatedCotacaoRouteImport.update({
  id: '/cotacao',
  path: '/cotacao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComprarRoute = AuthenticatedComprarRouteImport.update({
  id: '/comprar',
  path: '/comprar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClubeRoute = AuthenticatedClubeRouteImport.update({
  id: '/clube',
  path: '/clube',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedVenderIndexRoute =
  AuthenticatedVenderIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVenderRoute,
  } as any)
const AuthenticatedMensagensIndexRoute =
  AuthenticatedMensagensIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMensagensRoute,
  } as any)
const AuthenticatedCursosIndexRoute =
  AuthenticatedCursosIndexRouteImport.update({
    id: '/cursos/',
    path: '/cursos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCertificadosIndexRoute =
  AuthenticatedCertificadosIndexRouteImport.update({
    id: '/certificados/',
    path: '/certificados/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVenderNovoRoute = AuthenticatedVenderNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AuthenticatedVenderRoute,
} as any)
const AuthenticatedMensagensConversaIdRoute =
  AuthenticatedMensagensConversaIdRouteImport.update({
    id: '/$conversaId',
    path: '/$conversaId',
    getParentRoute: () => AuthenticatedMensagensRoute,
  } as any)
const AuthenticatedCursosIdRoute = AuthenticatedCursosIdRouteImport.update({
  id: '/cursos/$id',
  path: '/cursos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCertificadoCodigoRoute =
  AuthenticatedCertificadoCodigoRouteImport.update({
    id: '/certificado/$codigo',
    path: '/certificado/$codigo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnuncioIdRoute = AuthenticatedAnuncioIdRouteImport.update({
  id: '/anuncio/$id',
  path: '/anuncio/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminVantagensRoute =
  AuthenticatedAdminVantagensRouteImport.update({
    id: '/admin/vantagens',
    path: '/admin/vantagens',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminModeracaoRoute =
  AuthenticatedAdminModeracaoRouteImport.update({
    id: '/admin/moderacao',
    path: '/admin/moderacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminGestaoRoute =
  AuthenticatedAdminGestaoRouteImport.update({
    id: '/admin/gestao',
    path: '/admin/gestao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCursosRoute =
  AuthenticatedAdminCursosRouteImport.update({
    id: '/admin/cursos',
    path: '/admin/cursos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCotacoesRoute =
  AuthenticatedAdminCotacoesRouteImport.update({
    id: '/admin/cotacoes',
    path: '/admin/cotacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminContatosRoute =
  AuthenticatedAdminContatosRouteImport.update({
    id: '/admin/contatos',
    path: '/admin/contatos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCatalogoRoute =
  AuthenticatedAdminCatalogoRouteImport.update({
    id: '/admin/catalogo',
    path: '/admin/catalogo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAcessosRoute =
  AuthenticatedAdminAcessosRouteImport.update({
    id: '/admin/acessos',
    path: '/admin/acessos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedVenderEditarIdRoute =
  AuthenticatedVenderEditarIdRouteImport.update({
    id: '/editar/$id',
    path: '/editar/$id',
    getParentRoute: () => AuthenticatedVenderRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/bloqueado': typeof BloqueadoRoute
  '/cadastro': typeof CadastroRoute
  '/completar-cadastro': typeof CompletarCadastroRoute
  '/conheca': typeof ConhecaRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/clube': typeof AuthenticatedClubeRoute
  '/comprar': typeof AuthenticatedComprarRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conta': typeof AuthenticatedContaRoute
  '/cotacao': typeof AuthenticatedCotacaoRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/mensagens': typeof AuthenticatedMensagensRouteWithChildren
  '/negociacoes': typeof AuthenticatedNegociacoesRoute
  '/noticias': typeof AuthenticatedNoticiasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/startups': typeof AuthenticatedStartupsRoute
  '/vender': typeof AuthenticatedVenderRouteWithChildren
  '/para/$perfil': typeof ParaPerfilRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/acessos': typeof AuthenticatedAdminAcessosRoute
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/admin/contatos': typeof AuthenticatedAdminContatosRoute
  '/admin/cotacoes': typeof AuthenticatedAdminCotacoesRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosRoute
  '/admin/gestao': typeof AuthenticatedAdminGestaoRoute
  '/admin/moderacao': typeof AuthenticatedAdminModeracaoRoute
  '/admin/vantagens': typeof AuthenticatedAdminVantagensRoute
  '/anuncio/$id': typeof AuthenticatedAnuncioIdRoute
  '/certificado/$codigo': typeof AuthenticatedCertificadoCodigoRoute
  '/cursos/$id': typeof AuthenticatedCursosIdRoute
  '/mensagens/$conversaId': typeof AuthenticatedMensagensConversaIdRoute
  '/vender/novo': typeof AuthenticatedVenderNovoRoute
  '/certificados/': typeof AuthenticatedCertificadosIndexRoute
  '/cursos/': typeof AuthenticatedCursosIndexRoute
  '/mensagens/': typeof AuthenticatedMensagensIndexRoute
  '/vender/': typeof AuthenticatedVenderIndexRoute
  '/vender/editar/$id': typeof AuthenticatedVenderEditarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/bloqueado': typeof BloqueadoRoute
  '/cadastro': typeof CadastroRoute
  '/completar-cadastro': typeof CompletarCadastroRoute
  '/conheca': typeof ConhecaRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/clube': typeof AuthenticatedClubeRoute
  '/comprar': typeof AuthenticatedComprarRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conta': typeof AuthenticatedContaRoute
  '/cotacao': typeof AuthenticatedCotacaoRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/negociacoes': typeof AuthenticatedNegociacoesRoute
  '/noticias': typeof AuthenticatedNoticiasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/startups': typeof AuthenticatedStartupsRoute
  '/para/$perfil': typeof ParaPerfilRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/acessos': typeof AuthenticatedAdminAcessosRoute
  '/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/admin/contatos': typeof AuthenticatedAdminContatosRoute
  '/admin/cotacoes': typeof AuthenticatedAdminCotacoesRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosRoute
  '/admin/gestao': typeof AuthenticatedAdminGestaoRoute
  '/admin/moderacao': typeof AuthenticatedAdminModeracaoRoute
  '/admin/vantagens': typeof AuthenticatedAdminVantagensRoute
  '/anuncio/$id': typeof AuthenticatedAnuncioIdRoute
  '/certificado/$codigo': typeof AuthenticatedCertificadoCodigoRoute
  '/cursos/$id': typeof AuthenticatedCursosIdRoute
  '/mensagens/$conversaId': typeof AuthenticatedMensagensConversaIdRoute
  '/vender/novo': typeof AuthenticatedVenderNovoRoute
  '/certificados': typeof AuthenticatedCertificadosIndexRoute
  '/cursos': typeof AuthenticatedCursosIndexRoute
  '/mensagens': typeof AuthenticatedMensagensIndexRoute
  '/vender': typeof AuthenticatedVenderIndexRoute
  '/vender/editar/$id': typeof AuthenticatedVenderEditarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/bloqueado': typeof BloqueadoRoute
  '/cadastro': typeof CadastroRoute
  '/completar-cadastro': typeof CompletarCadastroRoute
  '/conheca': typeof ConhecaRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/clube': typeof AuthenticatedClubeRoute
  '/_authenticated/comprar': typeof AuthenticatedComprarRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/cotacao': typeof AuthenticatedCotacaoRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRouteWithChildren
  '/_authenticated/negociacoes': typeof AuthenticatedNegociacoesRoute
  '/_authenticated/noticias': typeof AuthenticatedNoticiasRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/startups': typeof AuthenticatedStartupsRoute
  '/_authenticated/vender': typeof AuthenticatedVenderRouteWithChildren
  '/para/$perfil': typeof ParaPerfilRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/acessos': typeof AuthenticatedAdminAcessosRoute
  '/_authenticated/admin/catalogo': typeof AuthenticatedAdminCatalogoRoute
  '/_authenticated/admin/contatos': typeof AuthenticatedAdminContatosRoute
  '/_authenticated/admin/cotacoes': typeof AuthenticatedAdminCotacoesRoute
  '/_authenticated/admin/cursos': typeof AuthenticatedAdminCursosRoute
  '/_authenticated/admin/gestao': typeof AuthenticatedAdminGestaoRoute
  '/_authenticated/admin/moderacao': typeof AuthenticatedAdminModeracaoRoute
  '/_authenticated/admin/vantagens': typeof AuthenticatedAdminVantagensRoute
  '/_authenticated/anuncio/$id': typeof AuthenticatedAnuncioIdRoute
  '/_authenticated/certificado/$codigo': typeof AuthenticatedCertificadoCodigoRoute
  '/_authenticated/cursos/$id': typeof AuthenticatedCursosIdRoute
  '/_authenticated/mensagens/$conversaId': typeof AuthenticatedMensagensConversaIdRoute
  '/_authenticated/vender/novo': typeof AuthenticatedVenderNovoRoute
  '/_authenticated/certificados/': typeof AuthenticatedCertificadosIndexRoute
  '/_authenticated/cursos/': typeof AuthenticatedCursosIndexRoute
  '/_authenticated/mensagens/': typeof AuthenticatedMensagensIndexRoute
  '/_authenticated/vender/': typeof AuthenticatedVenderIndexRoute
  '/_authenticated/vender/editar/$id': typeof AuthenticatedVenderEditarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aguardando-aprovacao'
    | '/bloqueado'
    | '/cadastro'
    | '/completar-cadastro'
    | '/conheca'
    | '/contato'
    | '/login'
    | '/mcp'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/agenda'
    | '/alertas'
    | '/clube'
    | '/comprar'
    | '/configuracoes'
    | '/conta'
    | '/cotacao'
    | '/financeiro'
    | '/mensagens'
    | '/negociacoes'
    | '/noticias'
    | '/painel'
    | '/planos'
    | '/relatorios'
    | '/startups'
    | '/vender'
    | '/para/$perfil'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/acessos'
    | '/admin/catalogo'
    | '/admin/contatos'
    | '/admin/cotacoes'
    | '/admin/cursos'
    | '/admin/gestao'
    | '/admin/moderacao'
    | '/admin/vantagens'
    | '/anuncio/$id'
    | '/certificado/$codigo'
    | '/cursos/$id'
    | '/mensagens/$conversaId'
    | '/vender/novo'
    | '/certificados/'
    | '/cursos/'
    | '/mensagens/'
    | '/vender/'
    | '/vender/editar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aguardando-aprovacao'
    | '/bloqueado'
    | '/cadastro'
    | '/completar-cadastro'
    | '/conheca'
    | '/contato'
    | '/login'
    | '/mcp'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/agenda'
    | '/alertas'
    | '/clube'
    | '/comprar'
    | '/configuracoes'
    | '/conta'
    | '/cotacao'
    | '/financeiro'
    | '/negociacoes'
    | '/noticias'
    | '/painel'
    | '/planos'
    | '/relatorios'
    | '/startups'
    | '/para/$perfil'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/acessos'
    | '/admin/catalogo'
    | '/admin/contatos'
    | '/admin/cotacoes'
    | '/admin/cursos'
    | '/admin/gestao'
    | '/admin/moderacao'
    | '/admin/vantagens'
    | '/anuncio/$id'
    | '/certificado/$codigo'
    | '/cursos/$id'
    | '/mensagens/$conversaId'
    | '/vender/novo'
    | '/certificados'
    | '/cursos'
    | '/mensagens'
    | '/vender'
    | '/vender/editar/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aguardando-aprovacao'
    | '/bloqueado'
    | '/cadastro'
    | '/completar-cadastro'
    | '/conheca'
    | '/contato'
    | '/login'
    | '/mcp'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/agenda'
    | '/_authenticated/alertas'
    | '/_authenticated/clube'
    | '/_authenticated/comprar'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conta'
    | '/_authenticated/cotacao'
    | '/_authenticated/financeiro'
    | '/_authenticated/mensagens'
    | '/_authenticated/negociacoes'
    | '/_authenticated/noticias'
    | '/_authenticated/painel'
    | '/_authenticated/planos'
    | '/_authenticated/relatorios'
    | '/_authenticated/startups'
    | '/_authenticated/vender'
    | '/para/$perfil'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/acessos'
    | '/_authenticated/admin/catalogo'
    | '/_authenticated/admin/contatos'
    | '/_authenticated/admin/cotacoes'
    | '/_authenticated/admin/cursos'
    | '/_authenticated/admin/gestao'
    | '/_authenticated/admin/moderacao'
    | '/_authenticated/admin/vantagens'
    | '/_authenticated/anuncio/$id'
    | '/_authenticated/certificado/$codigo'
    | '/_authenticated/cursos/$id'
    | '/_authenticated/mensagens/$conversaId'
    | '/_authenticated/vender/novo'
    | '/_authenticated/certificados/'
    | '/_authenticated/cursos/'
    | '/_authenticated/mensagens/'
    | '/_authenticated/vender/'
    | '/_authenticated/vender/editar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AguardandoAprovacaoRoute: typeof AguardandoAprovacaoRoute
  BloqueadoRoute: typeof BloqueadoRoute
  CadastroRoute: typeof CadastroRoute
  CompletarCadastroRoute: typeof CompletarCadastroRoute
  ConhecaRoute: typeof ConhecaRoute
  ContatoRoute: typeof ContatoRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ParaPerfilRoute: typeof ParaPerfilRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conheca': {
      id: '/conheca'
      path: '/conheca'
      fullPath: '/conheca'
      preLoaderRoute: typeof ConhecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completar-cadastro': {
      id: '/completar-cadastro'
      path: '/completar-cadastro'
      fullPath: '/completar-cadastro'
      preLoaderRoute: typeof CompletarCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloqueado': {
      id: '/bloqueado'
      path: '/bloqueado'
      fullPath: '/bloqueado'
      preLoaderRoute: typeof BloqueadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando-aprovacao': {
      id: '/aguardando-aprovacao'
      path: '/aguardando-aprovacao'
      fullPath: '/aguardando-aprovacao'
      preLoaderRoute: typeof AguardandoAprovacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para/$perfil': {
      id: '/para/$perfil'
      path: '/para/$perfil'
      fullPath: '/para/$perfil'
      preLoaderRoute: typeof ParaPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vender': {
      id: '/_authenticated/vender'
      path: '/vender'
      fullPath: '/vender'
      preLoaderRoute: typeof AuthenticatedVenderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/startups': {
      id: '/_authenticated/startups'
      path: '/startups'
      fullPath: '/startups'
      preLoaderRoute: typeof AuthenticatedStartupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/noticias': {
      id: '/_authenticated/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof AuthenticatedNoticiasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/negociacoes': {
      id: '/_authenticated/negociacoes'
      path: '/negociacoes'
      fullPath: '/negociacoes'
      preLoaderRoute: typeof AuthenticatedNegociacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cotacao': {
      id: '/_authenticated/cotacao'
      path: '/cotacao'
      fullPath: '/cotacao'
      preLoaderRoute: typeof AuthenticatedCotacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comprar': {
      id: '/_authenticated/comprar'
      path: '/comprar'
      fullPath: '/comprar'
      preLoaderRoute: typeof AuthenticatedComprarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clube': {
      id: '/_authenticated/clube'
      path: '/clube'
      fullPath: '/clube'
      preLoaderRoute: typeof AuthenticatedClubeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vender/': {
      id: '/_authenticated/vender/'
      path: '/'
      fullPath: '/vender/'
      preLoaderRoute: typeof AuthenticatedVenderIndexRouteImport
      parentRoute: typeof AuthenticatedVenderRoute
    }
    '/_authenticated/mensagens/': {
      id: '/_authenticated/mensagens/'
      path: '/'
      fullPath: '/mensagens/'
      preLoaderRoute: typeof AuthenticatedMensagensIndexRouteImport
      parentRoute: typeof AuthenticatedMensagensRoute
    }
    '/_authenticated/cursos/': {
      id: '/_authenticated/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof AuthenticatedCursosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/certificados/': {
      id: '/_authenticated/certificados/'
      path: '/certificados'
      fullPath: '/certificados/'
      preLoaderRoute: typeof AuthenticatedCertificadosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vender/novo': {
      id: '/_authenticated/vender/novo'
      path: '/novo'
      fullPath: '/vender/novo'
      preLoaderRoute: typeof AuthenticatedVenderNovoRouteImport
      parentRoute: typeof AuthenticatedVenderRoute
    }
    '/_authenticated/mensagens/$conversaId': {
      id: '/_authenticated/mensagens/$conversaId'
      path: '/$conversaId'
      fullPath: '/mensagens/$conversaId'
      preLoaderRoute: typeof AuthenticatedMensagensConversaIdRouteImport
      parentRoute: typeof AuthenticatedMensagensRoute
    }
    '/_authenticated/cursos/$id': {
      id: '/_authenticated/cursos/$id'
      path: '/cursos/$id'
      fullPath: '/cursos/$id'
      preLoaderRoute: typeof AuthenticatedCursosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/certificado/$codigo': {
      id: '/_authenticated/certificado/$codigo'
      path: '/certificado/$codigo'
      fullPath: '/certificado/$codigo'
      preLoaderRoute: typeof AuthenticatedCertificadoCodigoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/anuncio/$id': {
      id: '/_authenticated/anuncio/$id'
      path: '/anuncio/$id'
      fullPath: '/anuncio/$id'
      preLoaderRoute: typeof AuthenticatedAnuncioIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/vantagens': {
      id: '/_authenticated/admin/vantagens'
      path: '/admin/vantagens'
      fullPath: '/admin/vantagens'
      preLoaderRoute: typeof AuthenticatedAdminVantagensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/moderacao': {
      id: '/_authenticated/admin/moderacao'
      path: '/admin/moderacao'
      fullPath: '/admin/moderacao'
      preLoaderRoute: typeof AuthenticatedAdminModeracaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/gestao': {
      id: '/_authenticated/admin/gestao'
      path: '/admin/gestao'
      fullPath: '/admin/gestao'
      preLoaderRoute: typeof AuthenticatedAdminGestaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/cursos': {
      id: '/_authenticated/admin/cursos'
      path: '/admin/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AuthenticatedAdminCursosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/cotacoes': {
      id: '/_authenticated/admin/cotacoes'
      path: '/admin/cotacoes'
      fullPath: '/admin/cotacoes'
      preLoaderRoute: typeof AuthenticatedAdminCotacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/contatos': {
      id: '/_authenticated/admin/contatos'
      path: '/admin/contatos'
      fullPath: '/admin/contatos'
      preLoaderRoute: typeof AuthenticatedAdminContatosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/catalogo': {
      id: '/_authenticated/admin/catalogo'
      path: '/admin/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AuthenticatedAdminCatalogoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/acessos': {
      id: '/_authenticated/admin/acessos'
      path: '/admin/acessos'
      fullPath: '/admin/acessos'
      preLoaderRoute: typeof AuthenticatedAdminAcessosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vender/editar/$id': {
      id: '/_authenticated/vender/editar/$id'
      path: '/editar/$id'
      fullPath: '/vender/editar/$id'
      preLoaderRoute: typeof AuthenticatedVenderEditarIdRouteImport
      parentRoute: typeof AuthenticatedVenderRoute
    }
  }
}

interface AuthenticatedMensagensRouteChildren {
  AuthenticatedMensagensConversaIdRoute: typeof AuthenticatedMensagensConversaIdRoute
  AuthenticatedMensagensIndexRoute: typeof AuthenticatedMensagensIndexRoute
}

const AuthenticatedMensagensRouteChildren: AuthenticatedMensagensRouteChildren =
  {
    AuthenticatedMensagensConversaIdRoute:
      AuthenticatedMensagensConversaIdRoute,
    AuthenticatedMensagensIndexRoute: AuthenticatedMensagensIndexRoute,
  }

const AuthenticatedMensagensRouteWithChildren =
  AuthenticatedMensagensRoute._addFileChildren(
    AuthenticatedMensagensRouteChildren,
  )

interface AuthenticatedVenderRouteChildren {
  AuthenticatedVenderNovoRoute: typeof AuthenticatedVenderNovoRoute
  AuthenticatedVenderIndexRoute: typeof AuthenticatedVenderIndexRoute
  AuthenticatedVenderEditarIdRoute: typeof AuthenticatedVenderEditarIdRoute
}

const AuthenticatedVenderRouteChildren: AuthenticatedVenderRouteChildren = {
  AuthenticatedVenderNovoRoute: AuthenticatedVenderNovoRoute,
  AuthenticatedVenderIndexRoute: AuthenticatedVenderIndexRoute,
  AuthenticatedVenderEditarIdRoute: AuthenticatedVenderEditarIdRoute,
}

const AuthenticatedVenderRouteWithChildren =
  AuthenticatedVenderRoute._addFileChildren(AuthenticatedVenderRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedClubeRoute: typeof AuthenticatedClubeRoute
  AuthenticatedComprarRoute: typeof AuthenticatedComprarRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedCotacaoRoute: typeof AuthenticatedCotacaoRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRouteWithChildren
  AuthenticatedNegociacoesRoute: typeof AuthenticatedNegociacoesRoute
  AuthenticatedNoticiasRoute: typeof AuthenticatedNoticiasRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedStartupsRoute: typeof AuthenticatedStartupsRoute
  AuthenticatedVenderRoute: typeof AuthenticatedVenderRouteWithChildren
  AuthenticatedAdminAcessosRoute: typeof AuthenticatedAdminAcessosRoute
  AuthenticatedAdminCatalogoRoute: typeof AuthenticatedAdminCatalogoRoute
  AuthenticatedAdminContatosRoute: typeof AuthenticatedAdminContatosRoute
  AuthenticatedAdminCotacoesRoute: typeof AuthenticatedAdminCotacoesRoute
  AuthenticatedAdminCursosRoute: typeof AuthenticatedAdminCursosRoute
  AuthenticatedAdminGestaoRoute: typeof AuthenticatedAdminGestaoRoute
  AuthenticatedAdminModeracaoRoute: typeof AuthenticatedAdminModeracaoRoute
  AuthenticatedAdminVantagensRoute: typeof AuthenticatedAdminVantagensRoute
  AuthenticatedAnuncioIdRoute: typeof AuthenticatedAnuncioIdRoute
  AuthenticatedCertificadoCodigoRoute: typeof AuthenticatedCertificadoCodigoRoute
  AuthenticatedCursosIdRoute: typeof AuthenticatedCursosIdRoute
  AuthenticatedCertificadosIndexRoute: typeof AuthenticatedCertificadosIndexRoute
  AuthenticatedCursosIndexRoute: typeof AuthenticatedCursosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedClubeRoute: AuthenticatedClubeRoute,
  AuthenticatedComprarRoute: AuthenticatedComprarRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedCotacaoRoute: AuthenticatedCotacaoRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRouteWithChildren,
  AuthenticatedNegociacoesRoute: AuthenticatedNegociacoesRoute,
  AuthenticatedNoticiasRoute: AuthenticatedNoticiasRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedStartupsRoute: AuthenticatedStartupsRoute,
  AuthenticatedVenderRoute: AuthenticatedVenderRouteWithChildren,
  AuthenticatedAdminAcessosRoute: AuthenticatedAdminAcessosRoute,
  AuthenticatedAdminCatalogoRoute: AuthenticatedAdminCatalogoRoute,
  AuthenticatedAdminContatosRoute: AuthenticatedAdminContatosRoute,
  AuthenticatedAdminCotacoesRoute: AuthenticatedAdminCotacoesRoute,
  AuthenticatedAdminCursosRoute: AuthenticatedAdminCursosRoute,
  AuthenticatedAdminGestaoRoute: AuthenticatedAdminGestaoRoute,
  AuthenticatedAdminModeracaoRoute: AuthenticatedAdminModeracaoRoute,
  AuthenticatedAdminVantagensRoute: AuthenticatedAdminVantagensRoute,
  AuthenticatedAnuncioIdRoute: AuthenticatedAnuncioIdRoute,
  AuthenticatedCertificadoCodigoRoute: AuthenticatedCertificadoCodigoRoute,
  AuthenticatedCursosIdRoute: AuthenticatedCursosIdRoute,
  AuthenticatedCertificadosIndexRoute: AuthenticatedCertificadosIndexRoute,
  AuthenticatedCursosIndexRoute: AuthenticatedCursosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AguardandoAprovacaoRoute: AguardandoAprovacaoRoute,
  BloqueadoRoute: BloqueadoRoute,
  CadastroRoute: CadastroRoute,
  CompletarCadastroRoute: CompletarCadastroRoute,
  ConhecaRoute: ConhecaRoute,
  ContatoRoute: ContatoRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ParaPerfilRoute: ParaPerfilRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
